from os import remove

from selenium import webdriver
from selenium.webdriver.common.by import By
driver =webdriver.Firefox()
driver.get("https://www.saucedemo.com/")
driver.maximize_window()
username = driver.find_element(By.XPATH,"//input[@id='user-name']")
username.send_keys("standard_user")
password = driver.find_element(By.XPATH,"//input[@id = 'password']")
password.send_keys("secret_sauce")
login = driver.find_element(By.XPATH,"//input[@id='login-button']")
login.click()
Addcart = driver.find_element(By.XPATH,"//button[@id='add-to-cart-sauce-labs-backpack']")
Addcart.click()
#emove =driver.find_element(By.XPATH,"//button[@id='remove-sauce-labs-backpack']")
#emove.click()
Addcart= driver.find_element(By.XPATH,"//button[@id='add-to-cart-sauce-labs-bolt-t-shirt']")
Addcart.click()
Addcart = driver.find_element(By.XPATH,"//button[@id='add-to-cart-sauce-labs-onesie']")
Addcart.click()
cart = driver.find_element(By.XPATH,"//div[@id='shopping_cart_container']")
cart.click()
remove = driver.find_element(By.XPATH,"//button[@id='remove-sauce-labs-bolt-t-shirt']")
remove.click()
checkout = driver.find_element(By.XPATH,"//button[@id='checkout']")
checkout.click()
name = driver.find_element(By.XPATH,"//input[@id='first-name']")
name.send_keys("bhupendra")
lastname = driver.find_element(By.XPATH,"//input[@id='last-name']")
lastname.send_keys("Sen")
potal = driver.find_element(By.XPATH,"//input[@id='postal-code']")
potal.send_keys("66666")
done = driver.find_element(By.XPATH,"//input[@id='continue']")
done.click()
finish = driver.find_element(By.XPATH,"//button[@id='finish']")
finish.click()
addto = driver.find_element(By.XPATH,"//button[text()='Add to cart']")
addto.click()


